version: '3.7'

services:
  mc:
    image: itzg/minecraft-server
    hostname: minecraft
    container_name: minecraft
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2048M
    environment:
      UID: "998"
      GID: "998"
      TZ: "America/Argentina/Buenos_Aires"
      MEMORY: "2G"
      TYPE: "PAPER"
      EULA: "true"
      VERSION: "1.17.1"
      SPIGET_RESOURCES: 75871,18083,74208,59773,96014,2124,12936
      REMOVE_OLD_MODS: "TRUE"
      MOTD: "\u00A7e\u00A7lServidor\u00A7a\u00A7l Perri\u00A7c\u00A7l (1.17.1 Survival)"
      DIFFICULTY: normal
      OPS: "usuarioop"
      ICON: "./server-icon.png"
      MAX_PLAYERS: "5"
      PVP: "false"
      ONLINE_MODE: "FALSE"
      CONSOLE: "false"
      ENABLE_ROLLING_LOGS: "true"
      OVERRIDE_SERVER_PROPERTIES: "true"
    ports:
      - 9993:25565
    volumes:
      - ./mc-paper:/data

volumes:
  mc-paper: